"""LOB to NAICS mapping model."""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import String, Integer, Float, DateTime, func
from sqlalchemy.dialects.postgresql import ARRAY
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class LobNaicsMapping(Base):
    """Mapping from Line of Business patterns to NAICS codes.

    Supports both curated mappings and LLM-generated mappings with confidence scores.
    Used to translate user's LOB values into industry codes for occupation matching.

    Sources:
    - curated: Manually maintained common LOB patterns
    - llm: Generated by LLM and cached for future use
    - fuzzy: Matched via fuzzy string matching
    """

    __tablename__ = "lob_naics_mappings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    lob_pattern: Mapped[str] = mapped_column(String(255), nullable=False, unique=True, index=True)
    naics_codes: Mapped[list[str]] = mapped_column(ARRAY(String(6)), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    source: Mapped[str] = mapped_column(String(50), nullable=False, default="curated")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    def __repr__(self) -> str:
        return f"<LobNaicsMapping(pattern={self.lob_pattern}, codes={self.naics_codes})>"
